import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { BiUserPlus, BiX, BiCheck } from "react-icons/bi";
import Table from '../components/table';
import Form from '../components/form';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <section>
    <Head>
      <title>CRUD Application</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='py-5'>
      <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Employee Management</h1>

      <div className="container mx-auto flex justify-between py-5 px-5 ">
          <div className="left flex gap-3">
              <button className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-blue-800'>
                Add Employee <span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
              </button>
          </div>
        
      </div>
      <Form></Form>
      <div className="container mx-auto px-5">
        <Table></Table>
      </div>
     

    </main>
  </section>
  )
}
